---
Name: username-auth
After:
    - "framework/*"
---

Member:
    extensions:
        - UsernameMemberExtension
    unique_identifier_field: Username            

Director:
  rules:
    'UsernameSecurity//$Action/$ID/$OtherID': 'UsernameSecurity'
    'Security//lostusername/$ID/$OtherID': 'UsernameSecurity'
    'Security//usernamesent/$ID/$OtherID': 'UsernameSecurity'    